### ISSUE TITLE
Base16 Vim colorschemes use my iTerm2 theme colors.

### ISSUE THREAD

**Issue by Addisonbean** [chriskempson/base16-vim#111] opened 2016-09-20 22:08 UTC
I installed the base16-vim plugin for Neovim, and when I tried to use a base16 color scheme, it just uses the base16 colors from my iTerm2 theme. Other non-base16 color schemes do work though. I am using iTerm2, tmux, and Neovim, all with True Color support.

On my old computer I was able to use the base16 color schemes without base16-shell because everything I was using had True Color support. I just got a new computer, and the base16-vim color schemes have stopped working. I also tried using base16-shell on my new computer, but that didn't help.

**Comment by chriskempson** [comment] 2016-10-12 10:32
Related? https://github.com/chriskempson/base16-vim/issues/69

**Comment by Addisonbean** [comment] 2016-10-15 15:40
Yeah that looks like it's the same problem.

**Comment by chriskempson** [comment] 2016-12-28 16:55
Closing this as a duplicate of #69

**Closed by chriskempson** 2016-12-28 16:55 UTC

**Comment by Addisonbean** [comment] 2016-12-28 18:09
I was looking into this again, and I actually don't think this is related to #69 because I'm having the same issue in vim and neovim, not just neovim. I can't seem to isolate what the cause of the issue is. I'm on macOS 10.12.2, and I think my old computer was on macOS 10.11. That's the only difference I can think of that could be causing this.

**Comment by Addisonbean** [comment] 2016-12-28 18:12
To clarify the issue, I used to be able to use different base16 themes for iTerm2 and vim/neovim at the same time, but now my vim/neovim colorscheme is linked to my iTerm2 theme if I use a base16 vim colorscheme. Non-base16 colorschemes in vim work fine with the base16 iTerm2 themes.

**Comment by Addisonbean** [comment] 2017-01-08 01:21
I found the solution, I just had to add this to my ~/.vimrc

    if has("termguicolors")
        set termguicolors
    endif
