### ISSUE TITLE
Neovim's terminal mode and "true color"

### ISSUE THREAD

**Issue by skattyadz** [chriskempson/base16-vim#69] opened 2015-04-17 18:15 UTC
When neovim's in true color mode, its terminal emulation falls back to a default ansi color palette and displays coloured output in bright colors.

To get the terminal to use Ocean colors, I had to do the following:

``` vim
let g:terminal_color_0 = '#2b303b'
let g:terminal_color_1 = '#bf616a'
let g:terminal_color_2 = '#a3be8c'
...
```

Is neovim support an interest of base16-vim? You can probably expect someone to PR a fix to this as it gains popularity

**Comment by pickfire** [comment] 2015-06-12 06:52
+1, neovim is currently in beta, so a PR in early stage would let base16-vim gain polularity in neovim users.

**Comment by Dieterbe** [comment] 2015-11-03 23:23
+1 for neovim support :)

**Comment by taecilla** [comment] 2015-11-09 17:58
+1

**Comment by Dieterbe** [comment] 2015-11-14 09:24
i've been having trouble getting base16-vim to work properly in neovim. it seems to look alright, with a few colors being off, not quite sure if due to readme misunderstandings (see #78) or this.
(http://i.imgur.com/MZXY0jH.png
see colors of the ints, floats, self and the bar at the bottom are off. rest looks like screenie in readme)
is truecolor enabled by default in neovim? i've been trying to find this out and find docs, but no success.
my neovim setup is mostly default, with the exception of course of
```
set background=dark                                  
colorscheme base16-default                                                                                                         
```

**Comment by davidosomething** [comment] 2016-01-23 09:01
:+1:

**Comment by pickfire** [comment] 2016-01-24 04:14
I really hope I can use true color in my terminal, st.

Now, [most of the terminal suport true colors](https://gist.github.com/XVilka/8346728).

**Comment by Mattias-** [comment] 2016-03-14 21:02
I just made a PR to the upstream repo https://github.com/chriskempson/base16-builder/pull/346. This will set up the terminal colors properly. If you try it and it works properly please type that in a comment so that we can get this merged asap. @skattyadz @pickfire @davidosomething 
## Before
![screen shot 2016-03-14 at 21 54 52](https://cloud.githubusercontent.com/assets/1002805/13759644/7500f5a2-ea2f-11e5-8357-0816cd0b5e47.png)
## After
![screen shot 2016-03-14 at 21 53 36](https://cloud.githubusercontent.com/assets/1002805/13759651/8095cd52-ea2f-11e5-985f-248a2d67ee2a.png)

**Comment by pickfire** [comment] 2016-03-15 11:21
It seems like it have some problem with the script, there are some errors. By the way, the bar in the bottom looks ugly.

![2016-03-15-191922_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/13776052/f180a79a-eae2-11e5-89bd-8ec98eab2823.png)

**Comment by Mattias-** [comment] 2016-03-15 20:11
@pickfire Apparently base16-builder is in a bad shape at the moment. I forked this repo instead with files generated with a patched base16-builder. https://github.com/Mattias-/base16-vim. This also make it easier to test.

**Comment by dekz** [comment] 2016-03-18 00:01
```
export NVIM_TUI_ENABLE_TRUE_COLOR=1
```
Once I set this environment variable then the colors started to work as expected.

**Comment by martijn** [comment] 2016-03-22 15:09
You can also set it in your Neovim configuration:

    let $NVIM_TUI_ENABLE_TRUE_COLOR=1

Works great for me with iTerm2 version 3 beta and base16

**Comment by trusktr** [comment] 2016-05-25 19:08
`export NVIM_TUI_ENABLE_TRUE_COLOR=1` doesn't work for me. I posted a related issue on NeoVim before finding these: https://github.com/neovim/neovim/issues/4818

**Comment by teto** [comment] 2016-05-25 19:10
NVIM_TUI_ENABLE_TRUE_COLOR=1 has been superseeded by vim's option termguicolors cf https://github.com/neovim/neovim/wiki/Following-HEAD

**Comment by trusktr** [comment] 2016-05-25 19:26
@teto I only have time for `brew install`, for now. looking forward to trying `termguicolors`.

**Comment by chriskempson** [comment] 2016-06-28 13:20
Not sure whether to support this or not in this repo, Neovim seems like a Vim fork? Could always have a base16-neovim repo?

**Comment by pickfire** [comment] 2016-06-28 14:05
@chriskempson I think we could just check if it's neovim, if it support true color then just use it otherwise fallback to 16 colors.

**Comment by taecilla** [comment] 2016-06-28 14:43
@chriskempson the Neovim team tries to keep compatibility with Vim. In this case they deleted the `NVIM_TUI_ENABLE_TRUE_COLOR` [when they imported some Vim patches](https://github.com/neovim/neovim/pull/4690) so I think you can keep the same repo for both editors.

**Comment by chriskempson** [comment] 2016-06-28 18:22
Thanks for the info!

**Comment by pickfire** [comment] 2016-06-29 09:24
@taecilla, bingo!

@chriskempson, I guess I need to remind you that it is only in the `git` version, has not been released yet.

**Comment by chriskempson** [comment] 2016-06-29 10:56
@pickfire Okay thanks, I'll keep this issue open till it is confirmed as okay then.

**Comment by polyzen** [comment] 2016-08-22 14:37
They've made a release. neovim/neovim@5b8255e

**Comment by nicdumz** [comment] 2016-10-10 10:48
I'm a bit confused, what's the status of this issue?

- On neovim v0.1.5 I tried setting `termguicolors`and I think it seems to break most things, at least for base16-flat + fish (base16-shell is installed and setup in vimrc)
- I don't understand why chriskempson/base16-builder#346 is setting `let g:terminal_color_0` and friends. Where are those variables used?
- @Mattias- you probably need to pull from upstream on your forked repos. Namely, chriskempson/base16-shell@eeeff9d moved some base16-shell files, and things like https://github.com/Mattias-/base16-vim/blob/cb7ce6bc50d929a0a85ddb4f9e2b060fedaf90a2/colors/base16-flat.vim#L10 break

**Comment by ismay** [comment] 2017-02-25 14:09
Would be nice to support true colors. Gruvbox does it and it works very well.

**Closed** 2017-02-25 22:44 UTC
