### ISSUE TITLE
7959654 breaks compability with ALE and LanguageClient-Neovim (and possibly others)

### ISSUE THREAD

**Issue by andreyorst** [chriskempson/base16-vim#175] opened 2018-03-23 19:13 UTC
I've updated from 97f2feb to 7959654, and now I expirience this isse https://github.com/w0rp/ale/issues/1446
Look to this code:
![image](https://user-images.githubusercontent.com/19470159/37848766-5847a35e-2ee6-11e8-8cc6-8a0e7d95e021.png)
If I comment call to `greatest_common_division()` lint engine will highlight unused variables and functions by adding an underscore to them, and previously everything were fine, until the last update.
Before update:
![image](https://user-images.githubusercontent.com/19470159/37849023-261c5fcc-2ee7-11e8-86a4-49b68e8d2827.png)
Afret update:
![image](https://user-images.githubusercontent.com/19470159/37848821-904db50e-2ee6-11e8-8ffb-8311c9fc5f48.png)
Underscore disables highlighting, and every time I type text flashes to white now, because lint engine adds its marks every time i type a letter. But this wasn't an issue before update, because color wasnt changing.

**Comment by andreyorst** [comment] 2018-03-24 08:14
Checking out to e61dd537d6b29b7738b2f46b128f08458aad2027 wich is previous to #172 fixes the issue. I think that this merge should be reverted

**Comment by chriskempson** [comment] 2018-03-24 08:35
What does @tmahmood think of this?

**Comment by andreyorst** [comment] 2018-03-24 08:49
@chriskempson I thought it was @jlesquembre's PR, doesn't it?

**Comment by jlesquembre** [comment] 2018-03-24 08:51
I think that making text invisible on errors (what I tried to fix on #172 ) it's worst than losing syntax highlighting on error. But I agree that the current is status is not good, and maybe we can fix both problems. I don't have time right now, but I'll try to look to it later.

@andreyorst I cannot reproduce the text flash problem, could you provide a minimal example ?

**Comment by andreyorst** [comment] 2018-03-24 09:26
>  could you provide a minimal example?

![flashing](https://user-images.githubusercontent.com/19470159/37862476-69d0012a-2f5e-11e8-9029-21974f104397.gif)
I use touch typing, so this change form highlighted to white on every keypress very distracting.

**Comment by tmahmood** [comment] 2018-03-24 10:26
Why would Java specific highlight change cause issue in other language? 

If this change causes issue, I'm all for reverting. But it would be great if the underlying issue can be fixed too.

**Comment by andreyorst** [comment] 2018-03-24 13:54
Exuse me but this issue ralated to #172. I don't know why @chriskempson ping you, but this is not but this issue not related to #174 at all.

**Comment by chriskempson** [comment] 2018-03-24 13:55
Sorry @tmahmood and @andreyorst my mistake!

**Comment by jlesquembre** [comment] 2018-03-24 18:59
The original problem was that `Error` and `SpellBad` colors overlap:

```viml
call <sid>hi("Error",         s:gui00, s:gui08, s:cterm00, s:cterm08, "", "")
call <sid>hi("SpellBad",     "", s:gui00, "", s:cterm00, "undercurl", s:gui08)
```

And I think that many syntax errors are in both groups, making them unreadable. What do you think about leaving the `Error` group as it is now and updating `SpellBad` (and `SpellLocal`, `SpellCap` and `SpellRare` for consistency) to add only an underline?

```viml
call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)
```

Maybe I'm missing something, but I think that probably it's better to not modify the background for spelling errors. 

If looks good to you, I can make a PR with the changes

**Comment by andreyorst** [comment] 2018-03-25 13:07
@jlesquembre Changing SpellBad settings to theese:
```vim
call <sid>hi("SpellBad",     "", s:gui00, "", s:cterm00, "undercurl", s:gui08)
```
fixes error. This:
```vim
call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)
```
seems to fix it too, but i think that it will revert back the issue with invisible errors, right?

**Comment by jlesquembre** [comment] 2018-03-25 13:46
@andreyorst 
```viml
call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)
```
will add an undercurl with color `s:gui08` but the background and foreground colors will be not modified, so it solves the problem with the invisible colors too. (I tested it on neovim)
The only thing I'm not sure about, is if there was a reason to modify the background color. I think it makes more sense to not modify it, but maybe I'm missing something.

**Comment by andreyorst** [comment] 2018-03-25 13:55
> The only thing I'm not sure about, is if there was a reason to modify the background color

Well, I don't know anithing about that either. I'll set `SpellBad` to `"", "", "", "", "undercurl", s:gui08` and will report later if I encounter any issue.

**Comment by andreyorst** [comment] 2018-03-25 17:16
@jlesquembre 
This:
```vim
call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)
```
also add underline on cursorline. Like so:
![image](https://user-images.githubusercontent.com/19470159/37877819-cd6c3b8a-3068-11e8-9b1d-6d70b927d0fb.png)
![image](https://user-images.githubusercontent.com/19470159/37877823-da49473a-3068-11e8-8457-c8731174eae3.png)
That's annoing. I'll switch to
```vim
call <sid>hi("SpellBad",     "", s:gui00, "", s:cterm00, "undercurl", s:gui08)
```
As I can see already, it doesnt affect cursorline:
![image](https://user-images.githubusercontent.com/19470159/37877851-3fffd3e6-3069-11e8-8849-4dd29b286b94.png)

**Comment by jlesquembre** [comment] 2018-03-25 19:52
@andreyorst Are you using neovim? In vim looks good, and also in neovim if you disable the cursorline. It must be some bug on neovim.

**Comment by andreyorst** [comment] 2018-03-26 07:14
> Are you using neovim?

Yes.


>  In vim looks good, and also in neovim if you disable the cursorline.

What setting do you mean? This:
```vim
call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)
```
or this:
```vim
call <sid>hi("SpellBad",     "", s:gui00, "", s:cterm00, "undercurl", s:gui08)
```
If I disable cursorline in neovim, the first variant will of cource work as expected. While yes, in vim the first variant works with `set cursorline`, but it still changes highlightning on some functions. The both of privided settings actually.
vim:
![image](https://user-images.githubusercontent.com/19470159/37891588-7424874c-30dd-11e8-99d4-ce5939320a9e.png)
And again, if I ceckout to e61dd53 all theese problems disappear.

**Comment by jlesquembre** [comment] 2018-03-26 08:25
I meant the first one: `call <sid>hi("SpellBad",  "", "", "", "", "undercurl", s:gui08)`
I don't understand how that line can modify the highlighting for any function, since is only setting an underline. My guess is that probably is something related to LanguageClient-neovim (or other plugin)

Reverting the commit makes text invisible again in some situations:
https://github.com/chriskempson/base16-vim/issues/167#issuecomment-362420878

I'm more for updating `SpellBad` to my suggestion, instead of reverting the change. I agree that the underline is annoying, but really looks like a neovim bug (and anyways, is there only on some situations when ALE finds an error)

**Comment by andreyorst** [comment] 2018-03-26 09:08
> My guess is that probably is something related to LanguageClient-neovim (or other plugin)

but with theese settings
```vim
call <sid>hi("SpellBad",     "", s:gui00, "", s:cterm00, "undercurl", s:gui08)
```
there is no problem with ALE or LC. Highlighting, and underline works. I've experimented a bit and found that:
```vim
call <sid>hi("SpellBad",     "", s:gui00, "", "", "undercurl", s:gui08)
```
seems to work better then when every entry before `"undercurl"` is set to `""`. Underline isn't showup on cursorline enabled. Will this produce that behavior https://github.com/chriskempson/base16-vim/issues/167#issuecomment-362420878? I'm really far from vim colorscheme making, so I don't understand everything here. 
And I've figured out, that function recolor is not affected by `SpellBad`, it's `SpellCap` what causes recolor.

**Comment by jlesquembre** [comment] 2018-03-26 11:01
ALE is setting errors to `SpellBad` and warnings to `SpellCap`, see https://github.com/w0rp/ale/blob/master/autoload/ale/highlight.vim

A minimal example to see the invisible text error is this JS code (the second closing parenthesis is not visible)
```js
foo());
```

In your settings, you can ignore the cterm values, they are not used, since, I guess, you have `set termguicolors` in your neovim config (see `:help termguicolors`)

The underline problem is most probably a neovim bug, so nothing we can do about it. I'm not sure what highlighting error you mean is happening with `call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)`, but do you see it with LC disabled?

**Comment by andreyorst** [comment] 2018-03-26 11:30
Ok, well, I think I lost the thread of conversation. I use `termguicolors`. I can't check .js code, because i'm not familiar with this language, and don't want to set up new linter. I'm not sure where I've used "highlighting error" term, you talking about, so I would rely on your opinion of better fix for this. I'll investgate more into `cursorline` behavior in vim and neovim, and I'll open a bug if it is realy a bug. As for this issue, you defenitely know better how theme works, so I'll just accept given solution, because I can't propose anything, as I don't know much about it.

**Closed** 2018-05-24 13:51 UTC
