### ISSUE TITLE
Error: E117: Unknown function: Base16hi

### ISSUE THREAD

**Issue by petervanya** [chriskempson/base16-vim#163] opened 2017-12-05 23:14 UTC
Hello,
I installed all according to the README.md.
1. Adding `colorscheme base16-default-dark` to .vimrc
2. Adding `Plugin 'chriskempson/base16-vim'` to .vimrc in Vundle region
3. Creating directory ~/.vim/colors
4. Cloning the .vim files base16/colors/*.vim to ~/.vim/colors

Yet, at startup I am getting this error, which does not make much sense to me:

    E117: Unknown function: Base16hi

Can you please help?

**Comment by chriskempson** [comment] 2017-12-06 07:37
Possible duplicate of: https://github.com/chriskempson/base16-vim/issues/162

What version of Vim are you running?

**Comment by petervanya** [comment] 2017-12-06 13:15
Aha sorry, I did not notice.
But my version is 7.4.

**Comment by chriskempson** [comment] 2017-12-10 19:50
Can you try this again with the latest version and see if this is fixed for you?

**Comment by petervanya** [comment] 2017-12-14 17:39
Unfortunately, no success, still throwing the same error at launching Vim and the colors remain the same.

**Comment by harmishhk** [comment] 2017-12-18 10:56
I encountered the same error, My Vim version is 7.4.52 on Ubuntu 14.04. The error is indeed really annoying.

I managed to circumvent the error by simply adding `g:` in front of the function name `Base16hi` on line [155](https://github.com/chriskempson/base16-vim/blob/ac7a8f3601331548cea025e20d2c8c6520139ffa/colors/base16-tomorrow-night.vim#L155) of `base16-tomorrow-night.vim` file. That is using `call g:Base16hi(...` instead of `call Base16hi`.

Since, I do not know anything about vim plug-in development, I am not going to make a pull-request, and let the authors investigate more about the problem.

**Comment by jlesquembre** [comment] 2017-12-18 16:01
It should be fixed by #168

**Comment by petervanya** [comment] 2018-01-01 21:03
Okay, thanks.
This seems to work after repulling from Github, but the background is clearly light (see the attached figure). I assume this is not desirable?

Also, I am a bit confused about multiple ways to install it. Just adding the line 
`Plugin 'chriskempson/base16-vim'` to the Vundle section of ~/.vimrc and the line `colorscheme base16-default-dark` below or above the Vundle section (and running `:PluginInstall`) should suffice, right? However, this does not work without doing the "manual" installation as well...

Thanks in advance.

**Comment by chriskempson** [comment] 2018-01-04 07:01
The background looks dark to me? I use Vundle to install this and it works fine.

**Comment by petervanya** [comment] 2018-01-04 12:16
Sorry for my confusing explanation. The background on the screenshot is of course dark, but the font colours look as if `set background=light`, even though in my .vimrc there is `set background=dark`.

**Comment by chriskempson** [comment] 2018-01-09 06:12
I'm pretty sure this is the same issue as described herehttps://github.com/chriskempson/base16-vim/issues/170#issuecomment-356190030

**Closed** 2018-01-24 15:55 UTC
